import { WebsocketSides } from '@frameworks/websocket';

const PUBLIC_WEBSOCKET_URL = 'wss://ws.poloniex.com/ws/public';
const PRIVATE_WEBSOCKET_URL = 'wss://ws.poloniex.com/ws/private';

const MAX_STREAMS_PER_PAYLOAD = 100;

const WEBSOCKET_TIMEOUT_MS = 30 * 1000; // 30 seconds
const WEBSOCKET_LIFETIME_MS = undefined;
const WEBSOCKET_STREAM_LIMIT = undefined;
const WEBSOCKET_CONNECTIONS_LIMIT = 2000;
const WEBSOCKET_PINGING_SIDE = WebsocketSides.CLIENT;
const WEBSOCKET_PINGING_INTERVAL_MS = 25 * 1000; // 25 seconds
const IS_WEBSOCKET_PINGING_FRAMES = false;

const DEPTH_FULL_LEVEL = 20;

export const constants = {
  PUBLIC_WEBSOCKET_URL,
  PRIVATE_WEBSOCKET_URL,
  MAX_STREAMS_PER_PAYLOAD,
  WEBSOCKET_LIFETIME_MS,
  WEBSOCKET_PINGING_INTERVAL_MS,
  WEBSOCKET_TIMEOUT_MS,
  WEBSOCKET_STREAM_LIMIT,
  WEBSOCKET_CONNECTIONS_LIMIT,
  WEBSOCKET_PINGING_SIDE,
  IS_WEBSOCKET_PINGING_FRAMES,
  DEPTH_FULL_LEVEL,
};
