import { ExchangeNetworkConfig, NetworkCode } from '../types';

export const GATE_NETWORK_CONFIG: ExchangeNetworkConfig = {
  [NetworkCode.ETHEREUM]: ['erc20'],
  [NetworkCode.BSC]: ['bep20', 'bnb'],
  [NetworkCode.BNB]: ['bep2'],
  [NetworkCode.POLYGON]: ['matic'],
  [NetworkCode.ARBITRUM]: ['arbevm'],
  [NetworkCode.SOLANA]: ['sol'],
  [NetworkCode.OPTIMISM]: ['optimism'],
  [NetworkCode.AVALANCHE_C]: ['avaxc'],
  [NetworkCode.TRON]: ['trc20'],
  [NetworkCode.CHILIZ]: ['chz', 'chz2'],
  [NetworkCode.RONIN]: ['ron'],
  [NetworkCode.BASE]: ['baseevm'],
  [NetworkCode.ONTOLOGY]: ['ong'],
  [NetworkCode.FANTOM]: ['ftm'],
  [NetworkCode.POLKADOT]: ['dot'],
  [NetworkCode.POLKADOT_STATEMINT]: [],
  [NetworkCode.KAVA]: ['kava'],
  [NetworkCode.KAVAEVM]: ['kavaevm'],
  [NetworkCode.OPBNB]: ['opbnb'],
  [NetworkCode.CELO]: ['celo'],
  [NetworkCode.NEO]: [],
  [NetworkCode.NEO3]: ['gas', 'gas_old'],
  [NetworkCode.ZKSYNC_ERA]: ['zksera'],
  [NetworkCode.ZKSYNC_LITE]: [],
  [NetworkCode.EOS]: ['eos'],
  [NetworkCode.TON]: ['ton'],
  [NetworkCode.STARKNET]: ['strketh'],
  [NetworkCode.APTOS]: ['apt'],
  [NetworkCode.TERRA_CLASSIC]: ['lunc'],
  [NetworkCode.TERRA2]: ['luna'],
  [NetworkCode.THETA]: ['theta'],
  [NetworkCode.MANTA]: ['mantaeth', 'mantadot'],
  [NetworkCode.NULS]: ['nuls'],
  [NetworkCode.NULSEVM]: ['nulsevm'],
  [NetworkCode.MULTIVERSX]: ['egld'],
  [NetworkCode.BITCOIN]: [],
  [NetworkCode.BITCOIN_LIGHTNING]: [],
  [NetworkCode.BITCOIN_ORDINALS]: ['btc'],
  [NetworkCode.STELLAR]: ['xlm'],
  [NetworkCode.VECHAIN]: ['vet'],
  [NetworkCode.ALGORAND]: ['algo'],
  [NetworkCode.TEZOS]: ['xtz'],
  [NetworkCode.KOMODO]: [],
  [NetworkCode.WALTON]: [],
  [NetworkCode.HARMONY]: ['hrc20', 'one'],
  [NetworkCode.KLAYTN]: ['klay'],
  [NetworkCode.CARDANO]: ['ada'],
  [NetworkCode.BITCOIN_RUNES]: ['btcrunes'],
  [NetworkCode.SUI]: ['sui'],
  [NetworkCode.BITCI]: ['bitci'],
  [NetworkCode.CRONOS]: ['cro'],
  [NetworkCode.BLAST]: ['blasteth'],
  [NetworkCode.NEAR]: ['near'],
  [NetworkCode.LINEA]: ['lineaeth'],
  [NetworkCode.GATECHAIN]: ['gatechain'],
  [NetworkCode.WAVES]: ['waves'],
  [NetworkCode.HEDERA]: ['hbar'],
  [NetworkCode.MERLIN]: ['merl', 'merlbtc'],
  [NetworkCode.OKTCHAIN]: ['okc'],
  [NetworkCode.MODE]: ['modeeth'],
  [NetworkCode.NAS]: ['nas'],
  [NetworkCode.RIPPLE]: ['xrp'],
  [NetworkCode.ARBITRUM_NOVA]: ['arbnova'],
  [NetworkCode.ASTAR]: ['astar'],
  [NetworkCode.ASTAREVM]: ['astarevm'],
  [NetworkCode.KUSAMA]: ['kusama'],
  [NetworkCode.MOONBEAM]: ['glmr'],
  [NetworkCode.KARDIA]: ['kai'],
  [NetworkCode.SHIDEN]: ['sdn'],
  [NetworkCode.SHIDENEVM]: ['sdnevm'],
  [NetworkCode.METIS]: ['metis'],
  [NetworkCode.BITLAYER]: ['btrbtc'],
  [NetworkCode.BSQUARED]: ['b2btc'],
  [NetworkCode.BOBA]: ['bobaevm'],
  [NetworkCode.BONE]: ['bone'],
  [NetworkCode.AURORA]: ['auroraevm'],
  [NetworkCode.ELASTOS]: ['elaevm'],
  [NetworkCode.MANTLE]: ['mnt'],
  [NetworkCode.FLARE]: ['flr'],
  [NetworkCode.BIFROST]: ['bnc'],
  [NetworkCode.BIFROST_POLKADOT]: ['bncdot'],
  [NetworkCode.NEUTRON]: ['ntrn'],
  [NetworkCode.STACKS]: ['stx'],
  [NetworkCode.BITTORRENT]: ['btt'],
  [NetworkCode.ROLLUX]: ['suprevm'],
  [NetworkCode.GOCHAIN]: ['go'],
  [NetworkCode.INTERLAY]: ['interlay'],
  [NetworkCode.LITECOIN]: ['ltc'],
  [NetworkCode.CONFLUX]: ['cfxevm'],
  [NetworkCode.OSMOSIS]: ['osmo'],
  [NetworkCode.ZKLINK_NOVA]: ['zkleth'],
  [NetworkCode.FILEVM]: ['filevm'],
  [NetworkCode.TAIKO]: ['taikoeth'],
  [NetworkCode.ZILLIQA]: ['zil'],
  [NetworkCode.FLOW]: ['flow'],
  [NetworkCode.CORE]: ['core'],
  [NetworkCode.KCC]: ['kcc'],
  [NetworkCode.BITCOIN_SEGWIT]: [],
  [NetworkCode.IOST]: ['iost'],
  [NetworkCode.ROOTSTOCK]: ['rbtc'],
  [NetworkCode.MOONRIVER]: ['movr'],
  [NetworkCode.ACALA]: ['aca'],
  [NetworkCode.NANO]: ['nano'],
  [NetworkCode.FITFI]: ['fitfi'],
};
