apiVersion: v1
kind: Service
metadata:
  name: collection-controller-service
spec:
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: collection-controller-service
