import { WebsocketSides } from '@frameworks/websocket';

const DEFAULT_WEBSOCKET_URL = 'wss://api.gateio.ws/ws/v4/';

const WEBSOCKET_TIMEOUT_MS = 30 * 1000; // 30 seconds
const WEBSOCKET_LIFETIME_MS = undefined;
const WEBSOCKET_STREAM_LIMIT = 300;
const WEBSOCKET_CONNECTIONS_LIMIT = 300;
const WEBSOCKET_PINGING_SIDE = WebsocketSides.SERVER;
const WEBSOCKET_PINGING_INTERVAL_MS = undefined;
const IS_WEBSOCKET_PINGING_FRAMES = true;

const AUTH_MESSAGE_EXPIRATION_MS = 5000; // 5 seconds

const BALANCE_ACCOUNT_TYPE = 'spot';

const DEPTH_LEVEL = '5';
const DEPTH_UPDATE_INTERVAL = '1000ms';

export const constants = {
  DEFAULT_WEBSOCKET_URL,
  WEBSOCKET_TIMEOUT_MS,
  WEBSOCKET_LIFETIME_MS,
  WEBSOCKET_STREAM_LIMIT,
  WEBSOCKET_CONNECTIONS_LIMIT,
  WEBSOCKET_PINGING_SIDE,
  WEBSOCKET_PINGING_INTERVAL_MS,
  IS_WEBSOCKET_PINGING_FRAMES,
  AUTH_MESSAGE_EXPIRATION_MS,
  BALANCE_ACCOUNT_TYPE,
  DEPTH_LEVEL,
  DEPTH_UPDATE_INTERVAL,
};
