const AUTH_PLACEHOLDER = '<AUTH_KEY>';

const AUTHENTICATION_TIMEOUT = 60 * 1000; // 1 minute
const DEFAULT_TIMEOUT = 60 * 1000; // 1 minute

const BALANCE_DEFAULT_SYNC_DEBOUNCE_DELAY_MS = 500;
const DEPTH_DEFAULT_SYNC_THROTTLE_INTERVAL_MS = 2000;

export const constants = {
  AUTH_PLACEHOLDER,
  AUTHENTICATION_TIMEOUT,
  DEFAULT_TIMEOUT,
  BALANCE_DEFAULT_SYNC_DEBOUNCE_DELAY_MS,
  DEPTH_DEFAULT_SYNC_THROTTLE_INTERVAL_MS,
};
