import { WebsocketSides } from '@frameworks/websocket';

const MAX_STREAMS_PER_PAYLOAD = 100;

const WEBSOCKET_TIMEOUT_MS = 30 * 1000; // 30 seconds
const WEBSOCKET_LIFETIME_MS = undefined;
const WEBSOCKET_STREAM_LIMIT = 300;
const WEBSOCKET_CONNECTIONS_LIMIT = 50;
const WEBSOCKET_PINGING_SIDE = WebsocketSides.CLIENT;
const WEBSOCKET_PINGING_INTERVAL_MS = 18 * 1000; // 18 seconds
const IS_WEBSOCKET_PINGING_FRAMES = false;

export const constants = {
  MAX_STREAMS_PER_PAYLOAD,
  WEBSOCKET_LIFETIME_MS,
  WEBSOCKET_PINGING_INTERVAL_MS,
  WEBSOCKET_TIMEOUT_MS,
  WEBSOCKET_STREAM_LIMIT,
  WEBSOCKET_CONNECTIONS_LIMIT,
  WEBSOCKET_PINGING_SIDE,
  IS_WEBSOCKET_PINGING_FRAMES,
};
